# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Album

# Model Form Field configuration
form: $/stdevs/dom/models/album/fields.yaml

# Model Class name
modelClass: StDevs\Dom\Models\Album

# Default redirect location
defaultRedirect: stdevs/dom/albums

# Create page
create:
    title: backend::lang.form.create_title
    redirect: stdevs/dom/albums/update/:id
    redirectClose: stdevs/dom/albums

# Update page
update:
    title: backend::lang.form.update_title
    redirect: stdevs/dom/albums
    redirectClose: stdevs/dom/albums

# Preview page
preview:
    title: backend::lang.form.preview_title
